pipeline {
    agent any
    
    stages {
        stage('Cleanup') {
            steps {
                sh 'rm -rf taxi-booking'  // Delete old project
            }
        }

        stage('Print') {
            steps {
                echo 'new project'
            }
        }

        stage('Clone') {
            steps {
                sh 'git clone -b dev https://github.com/reddi122/taxi-booking.git'
            }
        }

        stage('Build') {
            steps {
                dir("taxi-booking") { 
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                sh 'echo Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo Deploying application...'
            }
        }

    }
}
