pipeline {
    agent any
    
    stages {
        stage('Cleanup') {
            steps {
                sh 'rm -rf taxi-booking'  // Delete old project
            }
        }

        stage('Print') {
            steps {
                echo 'new project'
            }
        }

        stage('Clone') {
            steps {
                sh 'git clone -b dev https://github.com/reddi122/taxi-booking.git'
            }
        }

        stage('Build') {
            steps {
                dir("taxi-booking") { 
                    sh 'mvn clean package'
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                dir('taxi-booking') {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

    }
}
